### PR TITLE
feature(priyanshu): added .gitpod.yml and .gitpod.Dockerfile

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
added configuration  file for gitpod users

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@puyuan1996 merge this pr

**Comment by PaParaZz1** [comment]
Please modify the name of this pull request as our format then we will merge it

**Comment by puyuan1996** [comment]
> @puyuan1996 merge this pr

Please consider some enhanced and detailed comments as follows:
```yaml
# This configuration file was automatically generated by Gitpod.
# You should adapt it to your project's needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml).
# After you've adjusted this file to your liking, commit it to your remote git repository to share the Gitpod configuration with others.

# If you need to start from a template, Gitpod provides ready-to-use ones: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  # The 'init' command is run once at the start of workspace creation.
  # It is typically used for installing project dependencies, as in this case.
  - init: pip install -r requirements.txt
 ```

**Comment by PentesterPriyanshu** [comment]
@PaParaZz1  ,@puyuan1996    I have added all the changes requested by both of you, thankyou

**Comment by puyuan1996** [comment]
Thanks for your valuable contribution! Best wishes.

**Pull request merged**
